<a href="https://colab.research.google.com/github/seoupark1/Spacecraft-Dynamics-and-Control/blob/main/Course_01_Kinematics/Source/quiz1_DCM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 📝 Quiz 1 - Problem 1
![Problem 1](https://github.com/seoupark1/Spacecraft-Dynamics-and-Control/blob/main/Course_01_Kinematics/note/quiz1_prob1.png?raw=true)

In [ ]:
import numpy as np

def result():
    b1 = np.array([1, 2, -2]) / 3
    b2 = np.array([0, 1, 1]) / np.sqrt(2)
    b3 = np.array([4, -1, 1]) / (3*np.sqrt(2))
    b = np.array([b1, b2, b3])
    f1 = np.array([3, -2, np.sqrt(3)]) / 4
    f2 = np.array([-1, 0, np.sqrt(3)]) / 2
    f3 = np.array([np.sqrt(3), 2*np.sqrt(3), 1]) / -4
    f = np.array([f1, f2, f3])
    BF = b @ f.transpose()

    return BF


print(result())

[[-0.37200847 -0.74401694 -0.55502117]
 [-0.04736717  0.61237244 -0.78914913]
 [ 0.92701998 -0.26728038 -0.26304971]]


---
## 📝 Quiz 1 - Problem 2
![Problem 2](https://github.com/seoupark1/Spacecraft-Dynamics-and-Control/blob/main/Course_01_Kinematics/note/quiz1_prob2.png?raw=true)

In [ ]:
import numpy as np

def result1():
       b1 = np.array([1, 2, -2]) / 3
       b2 = np.array([0, 1, 1]) / np.sqrt(2)
       b3 = np.array([4, -1, 1]) / (3*np.sqrt(2))
       b = np.array([b1, b2, b3])
       BF = b

       return BF


print(result1())

[[ 0.33333333  0.66666667 -0.66666667]
 [ 0.          0.70710678  0.70710678]
 [ 0.94280904 -0.23570226  0.23570226]]
