## 📝 Quiz 04 - Problem 1
![problem 1](https://github.com/seoupark1/Spacecraft-Dynamics-and-Control/blob/main/assets/images/course02/quiz04_prob1.png?raw=true)

In [1]:
!git clone https://github.com/seoupark1/Spacecraft-Dynamics-and-Control.git

Cloning into 'Spacecraft-Dynamics-and-Control'...
remote: Enumerating objects: 1427, done.
remote: Counting objects: 100% (135/135), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 1427 (delta 84), reused 51 (delta 44), pack-reused 1292 (from 1)
Receiving objects: 100% (1427/1427), 1.31 MiB | 14.24 MiB/s, done.
Resolving deltas: 100% (533/533), done.


In [2]:
import sys
import os

repo_path = '/content/Spacecraft-Dynamics-and-Control'

if repo_path not in sys.path:
    sys.path.append(repo_path)

In [5]:
import numpy as np
from utils import gnc_math, coordinate_transformation as ct

# Modified Rodrigues Parameters to Direction Cosine Matrix
def MRP2C(sigma):
    dcm_BN = (np.eye(3) + (8*gnc_math.tilde_matrix(sigma)@gnc_math.tilde_matrix(sigma) - 4*(1-np.vdot(sigma,sigma))*gnc_math.tilde_matrix(sigma))
    / (1+np.vdot(sigma,sigma))**2)

    return dcm_BN

# initial values
Ic_B = np.array([[10, 1, -1],
                 [1, 5, 1],
                 [-1, 1, 8]])
sigma_DB = np.array([0.1, 0.2, 0.3]).reshape(3,1)
body = ct.Attitude.from_mrp(sigma_DB)
dcm_DB = body.dcm

Ic_D = dcm_DB @ Ic_B @ np.transpose(dcm_DB)
print(Ic_D)

[[ 5.42779505 -1.77341012  1.37988231]
 [-1.77341012  9.27952214 -0.53047352]
 [ 1.37988231 -0.53047352  8.29268281]]


## 📝 Quiz 04 - Problem 2
![problem 2](https://github.com/seoupark1/Spacecraft-Dynamics-and-Control/blob/main/assets/images/course02/quiz04_prob2.png?raw=true)

In [7]:
import numpy as np
from utils import gnc_math, coordinate_transformation as ct

# Principal Inertias & Corresponding DCM
def coordinate_transform(Ic_B):
    # get eigenvalues & eigenvectors
    eig_vals, eig_vecs = np.linalg.eigh(Ic_B)

    # change eigenvalue's index
    I_min, I_med, I_max = eig_vals[0], eig_vals[1], eig_vals[2]
    eig_vals = np.array([I_max, I_med, I_min])

    # change eigenvector's index & make [FB] dcm
    v_min, v_med, v_max = eig_vecs[:, 0], eig_vecs[:, 1], eig_vecs[:, 2]
    dcm_FB = np.array([v_max, v_med, v_min])

    return eig_vals, dcm_FB

# initial values
Ic_B = np.array([[10, 1, -1],
                 [1, 5, 1],
                 [-1, 1, 8]])
principalInertias = coordinate_transform(Ic_B)[0]
print(principalInertias)

[10.47419366  8.11268085  4.41312549]


## 📝 Quiz 04 - Problem 3
![problem 3](https://github.com/seoupark1/Spacecraft-Dynamics-and-Control/blob/main/assets/images/course02/quiz04_prob3.png?raw=true)

In [8]:
import numpy as np
from utils import gnc_math, coordinate_transformation as ct

# Principal Inertias & Corresponding DCM
def coordinate_transform(Ic_B):
    # get eigenvalues & eigenvectors
    eig_vals, eig_vecs = np.linalg.eigh(Ic_B)

    # change eigenvalue's index
    I_min, I_med, I_max = eig_vals[0], eig_vals[1], eig_vals[2]
    eig_vals = np.array([I_max, I_med, I_min])

    # change eigenvector's index & make [FB] dcm
    v_min, v_med, v_max = eig_vecs[:, 0], eig_vecs[:, 1], eig_vecs[:, 2]
    dcm_FB = np.array([v_max, v_med, v_min])

    # if dcm_FB's det = -1, we have to change it to right-handed
    if np.linalg.det(dcm_FB) < 0:
        dcm_FB[2, :] = -dcm_FB[2, :]

    return eig_vals, dcm_FB

# initial values
Ic_B = np.array([[10, 1, -1],
                 [1, 5, 1],
                 [-1, 1, 8]])
FB = coordinate_transform(Ic_B)[1]
print(FB)

[[ 0.93616416  0.11001782 -0.33390528]
 [ 0.27260861  0.37256363  0.88706307]
 [ 0.22199371 -0.92146211  0.31878891]]
