## 📝 Quiz 03 - Problem 1
![problem 1](https://github.com/seoupark1/Spacecraft-Dynamics-and-Control/blob/main/assets/images/course02/quiz03_prob1.png?raw=true)

In [7]:
!wget -O coordinate_transformation.py https://raw.githubusercontent.com/seoupark1/Spacecraft-Dynamics-and-Control/main/utils/coordinate_transformation.py

--2026-07-06 13:44:22--  https://raw.githubusercontent.com/seoupark1/Spacecraft-Dynamics-and-Control/main/utils/coordinate_transformation.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6081 (5.9K) [text/plain]
Saving to: ‘coordinate_transformation.py’

coordinate_transfor 100%[===================>]   5.94K  --.-KB/s    in 0s      

2026-07-06 13:44:22 (65.1 MB/s) - ‘coordinate_transformation.py’ saved [6081/6081]



In [8]:
import numpy as np
import coordinate_transformation as ct
import importlib

# rebooting
importlib.reload(ct)

# initial values
M = 12.5
euler_angles = np.array([-10, 10, 5])
Ic_B = np.array([[10, 1, -1],
                [1, 5, 1],
                [-1, 1, 8]])
body = ct.Attitude.from_ea321(euler_angles)

# change Rcp_N to Rcp_B
Rcp_N = np.array([-0.5, 0.5, 0.25])
Rcp_B = body.dcm @ Rcp_N

def parallel_axis(Ic_B, M, Rcp_B):
    Ip_B = Ic_B + M * ct.tilde_matrix(Rcp_B) @ np.transpose(ct.tilde_matrix(Rcp_B))

    return Ip_B

print(parallel_axis(Ic_B, M, Rcp_B))

[[12.32125207  4.19755562 -0.15813867]
 [ 4.19755562  9.86047157  0.42847142]
 [-0.15813867  0.42847142 14.88077637]]
