## 📝 Quiz 04 - Problem 1
![problem 1](https://github.com/seoupark1/Spacecraft-Dynamics-and-Control/blob/main/assets/images/course02/quiz04_prob1.png?raw=true)

In [2]:
!wget -O utils_kinematics.py https://raw.githubusercontent.com/seoupark1/Spacecraft-Dynamics-and-Control/main/utils/utils_kinematics.py

--2026-06-24 14:24:37--  https://raw.githubusercontent.com/seoupark1/Spacecraft-Dynamics-and-Control/main/utils/utils_kinematics.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1277 (1.2K) [text/plain]
Saving to: ‘utils_kinematics.py’

utils_kinematics.py 100%[===================>]   1.25K  --.-KB/s    in 0s      

2026-06-24 14:24:37 (41.5 MB/s) - ‘utils_kinematics.py’ saved [1277/1277]



In [13]:
import numpy as np
import utils_kinematics as uk
import importlib

# rebooting
importlib.reload(uk)

# Modified Rodrigues Parameters to Direction Cosine Matrix
def MRP2C(sigma):
    dcm_BN = (np.eye(3) + (8*uk.tilde(sigma)@uk.tilde(sigma) - 4*(1-np.vdot(sigma,sigma))*uk.tilde(sigma))
    / (1+np.vdot(sigma,sigma))**2)

    return dcm_BN

# initial values
Ic_B = np.array([[10, 1, -1],
                 [1, 5, 1],
                 [-1, 1, 8]])
sigma_DB = np.array([0.1, 0.2, 0.3]).reshape(3,1)
dcm_DB = MRP2C(sigma_DB)

Ic_D = dcm_DB @ Ic_B @ np.transpose(dcm_DB)
print(Ic_D)

[[ 5.42779505 -1.77341012  1.37988231]
 [-1.77341012  9.27952214 -0.53047352]
 [ 1.37988231 -0.53047352  8.29268281]]


## 📝 Quiz 04 - Problem 2
![problem 2](https://github.com/seoupark1/Spacecraft-Dynamics-and-Control/blob/main/assets/images/course02/quiz04_prob2.png?raw=true)

In [10]:
import numpy as np
import utils_kinematics as uk
import importlib

# rebooting
importlib.reload(uk)

# Principal Inertias & Corresponding DCM
def coordinate_transform(Ic_B):
    # get eigenvalues & eigenvectors
    eig_vals, eig_vecs = np.linalg.eigh(Ic_B)

    # change eigenvalue's index
    I_min, I_med, I_max = eig_vals[0], eig_vals[1], eig_vals[2]
    eig_vals = np.array([I_max, I_med, I_min])

    # change eigenvector's index & make [FB] dcm
    v_min, v_med, v_max = eig_vecs[:, 0], eig_vecs[:, 1], eig_vecs[:, 2]
    dcm_FB = np.array([v_max, v_med, v_min])

    return eig_vals, dcm_FB

# initial values
Ic_B = np.array([[10, 1, -1],
                 [1, 5, 1],
                 [-1, 1, 8]])
principalInertias = coordinate_transform(Ic_B)[0]
print(principalInertias)

[10.47419366  8.11268085  4.41312549]


## 📝 Quiz 04 - Problem 3
![problem 3](https://github.com/seoupark1/Spacecraft-Dynamics-and-Control/blob/main/assets/images/course02/quiz04_prob3.png?raw=true)

In [15]:
import numpy as np
import utils_kinematics as uk
import importlib

# rebooting
importlib.reload(uk)

# Principal Inertias & Corresponding DCM
def coordinate_transform(Ic_B):
    # get eigenvalues & eigenvectors
    eig_vals, eig_vecs = np.linalg.eigh(Ic_B)

    # change eigenvalue's index
    I_min, I_med, I_max = eig_vals[0], eig_vals[1], eig_vals[2]
    eig_vals = np.array([I_max, I_med, I_min])

    # change eigenvector's index & make [FB] dcm
    v_min, v_med, v_max = eig_vecs[:, 0], eig_vecs[:, 1], eig_vecs[:, 2]
    dcm_FB = np.array([v_max, v_med, v_min])

    # if dcm_FB's det = -1, we have to change it to right-handed
    if np.linalg.det(dcm_FB) < 0:
        dcm_FB[2, :] = -dcm_FB[2, :]

    return eig_vals, dcm_FB

# initial values
Ic_B = np.array([[10, 1, -1],
                 [1, 5, 1],
                 [-1, 1, 8]])
FB = coordinate_transform(Ic_B)[1]
print(FB)

[[ 0.93616416  0.11001782 -0.33390528]
 [ 0.27260861  0.37256363  0.88706307]
 [ 0.22199371 -0.92146211  0.31878891]]
