## 📝 Quiz 03 - Problem 1
![problem 1](https://github.com/seoupark1/Spacecraft-Dynamics-and-Control/blob/main/assets/images/course02/quiz03_prob1.png?raw=true)

In [4]:
!wget -O utils_kinematics.py https://raw.githubusercontent.com/seoupark1/Spacecraft-Dynamics-and-Control/main/utils/utils_kinematics.py

--2026-06-23 14:13:08--  https://raw.githubusercontent.com/seoupark1/Spacecraft-Dynamics-and-Control/main/utils/utils_kinematics.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1277 (1.2K) [text/plain]
Saving to: ‘utils_kinematics.py’

utils_kinematics.py 100%[===================>]   1.25K  --.-KB/s    in 0s      

2026-06-23 14:13:08 (64.0 MB/s) - ‘utils_kinematics.py’ saved [1277/1277]



In [13]:
import numpy as np
import utils_kinematics
import importlib

# rebooting
importlib.reload(utils_kinematics)

# initial values
M = 12.5
euler_angles = np.array([-10, 10, 5])
Ic_B = np.array([[10, 1, -1],
                [1, 5, 1],
                [-1, 1, 8]])

# change Rcp_N to Rcp_B
dcm_BN = utils_kinematics.EA2C_321(euler_angles)
Rcp_N = np.array([-0.5, 0.5, 0.25])
Rcp_B = dcm_BN @ Rcp_N

def parallel_axis(Ic_B, M, Rcp_B):
    Ip_B = Ic_B + M * utils_kinematics.tilde(Rcp_B) @ np.transpose(utils_kinematics.tilde(Rcp_B))

    return Ip_B

print(parallel_axis(Ic_B, M, Rcp_B))

[[12.32125207  4.19755562 -0.15813867]
 [ 4.19755562  9.86047157  0.42847142]
 [-0.15813867  0.42847142 14.88077637]]
